export const empresa = {
    "uf": "SC",
    "cep": "88330486",
    "qsa": [
        {
            "pais": null,
            "nome_socio": "VALMOR ALBERTO DALAGO NETO",
            "codigo_pais": null,
            "faixa_etaria": "Entre 21 a 30 anos",
            "cnpj_cpf_do_socio": "***674589**",
            "qualificacao_socio": "Sócio",
            "codigo_faixa_etaria": 3,
            "data_entrada_sociedade": "2020-11-26",
            "identificador_de_socio": 2,
            "cpf_representante_legal": "***000000**",
            "nome_representante_legal": "",
            "codigo_qualificacao_socio": 22,
            "qualificacao_representante_legal": "Não informada",
            "codigo_qualificacao_representante_legal": 0
        },
        {
            "pais": null,
            "nome_socio": "EMIR ADAN MUSE",
            "codigo_pais": null,
            "faixa_etaria": "Entre 31 a 40 anos",
            "cnpj_cpf_do_socio": "***472799**",
            "qualificacao_socio": "Sócio-Administrador",
            "codigo_faixa_etaria": 4,
            "data_entrada_sociedade": "2021-06-02",
            "identificador_de_socio": 2,
            "cpf_representante_legal": "***000000**",
            "nome_representante_legal": "",
            "codigo_qualificacao_socio": 49,
            "qualificacao_representante_legal": "Não informada",
            "codigo_qualificacao_representante_legal": 0
        },
        {
            "pais": null,
            "nome_socio": "GABRIEL VON FRUHAUF",
            "codigo_pais": null,
            "faixa_etaria": "Entre 21 a 30 anos",
            "cnpj_cpf_do_socio": "***692389**",
            "qualificacao_socio": "Sócio",
            "codigo_faixa_etaria": 3,
            "data_entrada_sociedade": "2022-04-08",
            "identificador_de_socio": 2,
            "cpf_representante_legal": "***000000**",
            "nome_representante_legal": "",
            "codigo_qualificacao_socio": 22,
            "qualificacao_representante_legal": "Não informada",
            "codigo_qualificacao_representante_legal": 0
        }
    ],
    "cnpj": "39920173000163",
    "pais": null,
    "email": null,
    "porte": "MICRO EMPRESA",
    "bairro": "CENTRO",
    "numero": "100",
    "ddd_fax": "",
    "municipio": "BALNEARIO CAMBORIU",
    "logradouro": "2028",
    "cnae_fiscal": 6920601,
    "codigo_pais": null,
    "complemento": "SALA 01",
    "codigo_porte": 1,
    "razao_social": "HERMES CONTABILIDADE LTDA",
    "nome_fantasia": "",
    "capital_social": 200000,
    "ddd_telefone_1": "4735144771",
    "ddd_telefone_2": "",
    "opcao_pelo_mei": false,
    "descricao_porte": "",
    "codigo_municipio": 8039,
    "cnaes_secundarios": [
        {
            "codigo": 8211300,
            "descricao": "Serviços combinados de escritório e apoio administrativo"
        }
    ],
    "natureza_juridica": "Sociedade Empresária Limitada",
    "situacao_especial": "",
    "opcao_pelo_simples": true,
    "situacao_cadastral": 2,
    "data_opcao_pelo_mei": null,
    "data_exclusao_do_mei": null,
    "cnae_fiscal_descricao": "Atividades de contabilidade",
    "codigo_municipio_ibge": 4202008,
    "data_inicio_atividade": "2020-11-26",
    "data_situacao_especial": null,
    "data_opcao_pelo_simples": "2020-11-26",
    "data_situacao_cadastral": "2020-11-26",
    "nome_cidade_no_exterior": "",
    "codigo_natureza_juridica": 2062,
    "data_exclusao_do_simples": null,
    "motivo_situacao_cadastral": 0,
    "ente_federativo_responsavel": "",
    "identificador_matriz_filial": 1,
    "qualificacao_do_responsavel": 49,
    "descricao_situacao_cadastral": "ATIVA",
    "descricao_tipo_de_logradouro": "RUA",
    "descricao_motivo_situacao_cadastral": "SEM MOTIVO",
    "descricao_identificador_matriz_filial": "MATRIZ"
}